### ISSUE TITLE
ngron option to read content from clipboard

### ISSUE THREAD

**Issue by Clonkk** [virizar/ngron#1]
Thanks for making this, pretty cool tool.

As someone who often needs to copy json from various tool, it would be super useful to have a CLI option to run ngron on the content of my clipboard. 

Do you think it's something you could add ? Let me know if that's too much work and you need a hand

**Comment by virizar** [comment]
hi @Clonkk 

That is quite a nice idea to implement. I found that there is a library called [nimclipboard](https://github.com/genotrance/nimclipboard) that wraps the clipboard functionality for difrferent patforms and window managers and makes it easy to implement reading from the clipboard. It is outdated though , but it seems to work fine. I added the `-c` flag to use the clipboard as input, give it a go and let me know.

**Comment by Clonkk** [comment]
Awesome, i'll try it out
